### ISSUE TITLE
plantuml add comment value

### ISSUE THREAD

**Issue by gaozhidf** [k1LoW/tbls#121]
It's me again O_0, and thanks for your quick response.

And could you add the _comment_ value when the output file is puml or png file,

something like [ddl2plantuml](https://github.com/wangyuheng/ddl2plantuml)
![ddl2plantuml](https://camo.githubusercontent.com/c7a536175882d36228071cd754a47c57aaef58c0/687474703a2f2f696d6167652e637269636b2e77616e672f64646c32706c616e74756d6c2d312e6a7067)

**Comment by k1LoW** [comment]
Hi @gaozhidf . Thank you for your request 👍

**Comment by k1LoW** [comment]
Released as v1.17.0.
