### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by luchaobo** [k1LoW/tbls#125]
![image](https://user-images.githubusercontent.com/3262275/60700685-5cbfe200-9f2b-11e9-8dcb-a771581f0fbd.png)

**Comment by k1LoW** [comment]
Hi @luchaobo . Thank you for your report !

- Please show me the result of `tbls version`
- Please show me the result of `DEBUG=1 tbls doc YOUR_DSN`
- Could you show me your database table names ?

**Comment by luchaobo** [comment]
> Hi @luchaobo . Thank you for your report !
> 
> Could you show me following ?
> 
> * The result of `tbls version`
> * The result of `DEBUG=1 tbls doc YOUR_DSN`
> * MySQL version
> * Your database table names

Thanks to reply.
I use the download link "https://github.com/k1LoW/tbls/releases/download/v1.17.0/tbls_v1.17.0_linux_amd64.tar.gz"

The result of "tbls version": dev

The result of "DEBUG=1 tbls doc YOUR_DSN" :
![image](https://user-images.githubusercontent.com/3262275/60783188-393fa600-a17c-11e9-9538-1c61ebbc102c.png)

MySQL version:MySQL 5.6

Table names: 600+ tables in database.   

Maybe too many tables cause the error? I run the command with other db and it works fine.

**Comment by luchaobo** [comment]
Problem solved. Table name contain '-' causes the error.  eg:tmp-tablename

**Comment by k1LoW** [comment]
> Problem solved. Table name contain '-' causes the error. eg:tmp-tablename

Oh! Thank you !! This is bug. I'll fix it.

**Comment by k1LoW** [comment]
> Table names: 600+ tables in database.

Too big...
