### ISSUE TITLE
pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by mohamedhagag** [k1LoW/tbls#152]
### What happened
error pq: SSL is not enabled on the server
### What you expected to happed
connect
### What stacktrace or error message from tbls did you see?
pq: SSL is not enabled on the server
### Anything else we need to know?
how to disable ssl in connection ?
### Environment

- `tbls version`
- Database version
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
- Config ( .tbls.yml )

**Comment by mohamedhagag** [comment]
found a solution using ?sslmode=disable in the dsn

**Comment by k1LoW** [comment]
Hi @mohamedhagag 

> found a solution using ?sslmode=disable in the dsn

YES !!

**Comment by rafi** [comment]
This is worth adding to README.md

**Comment by navaneeth-spotnana** [comment]
Please add to the readme. ❤️
