### ISSUE TITLE
not found column 'res_company_ldap."user"'

### ISSUE THREAD

**Issue by mohamedhagag** [k1LoW/tbls#153]
### What happened
while running `tbls doc $DSN $DIR`
### What you expected to happed
generate the docs
### What stacktrace or error message from tbls did you see?
err: `not found column 'res_company_ldap."user"'`
### Anything else we need to know?
the column already exists, the DB is an odoo DB and working fine
### Environment

- `tbls version` latest
- Database version PG 12.x
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
`not found column 'res_company_ldap."user"'
github.com/k1LoW/tbls/schema.(*Table).FindColumnByName
        /Users/k1low/src/github.com/k1LoW/tbls/schema/schema.go:174
github.com/k1LoW/tbls/drivers/postgres.(*Postgres).Analyze
        /Users/k1low/src/github.com/k1LoW/tbls/drivers/postgres/postgres.go:304
github.com/k1LoW/tbls/datasource.Analyze
        /Users/k1low/src/github.com/k1LoW/tbls/datasource/datasource.go:83
github.com/k1LoW/tbls/cmd.glob..func4
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/doc.go:72
github.com/spf13/cobra.(*Command).execute
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/k1LoW/tbls/cmd.Execute
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/root.go:59
main.main
        /Users/k1low/src/github.com/k1LoW/tbls/main.go:33
runtime.main
        /Users/k1low/.anyenv/envs/goenv/versions/1.13.6/src/runtime/proc.go:203
runtime.goexit
        /Users/k1low/.anyenv/envs/goenv/versions/1.13.6/src/runtime/asm_amd64.s:1357
`
- Config ( .tbls.yml )

**Comment by k1LoW** [comment]
Hi @mohamedhagag ! Thank you for your report !!

Fixed version released as v1.24.1. Please check.

Best regards.
