### ISSUE TITLE
tbls doesn't manage the md files after creation

### ISSUE THREAD

**Issue by ykostsik** [k1LoW/tbls#159]
### What happened
tbls doesn't manage the md files after creation
### What you expected to happed
A new md file should be created after creation a corresponding table in the database and then running `tbls doc`
### What stacktrace or error message from tbls did you see?
output files already exists
### Anything else we need to know?
Am I right that `tbls doc` should update the md files in`docPath` after running? So if we create/ delete a new object in the database, the related md file should appear/desappear?
As I see, now it creates the files in a proper way only the first time. Next, even though the table was deleted from the database, the file remains unchanged.  And similary, if I create a new table, I could see the changes only in `tbls diff` When I run `tbls doc` again to commit them, the local files aren't changed and I don't see any new files related to the created table.
### Environment

- `tbls version` 1.24.1
- Database version Postgres 11.5
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
  output files already exists
- Config ( .tbls.yml )

**Comment by k1LoW** [comment]
> Next, even though the table was deleted from the database, the file remains unchanged. 

Yes. 

Because `tbls doc` may output `.md` to the directory where other documents are.

`tbls doc` has no function to delete `.md` now.

> and I don't see any new files related to the created table.

You can use `-f` option  for override `.md` when execute `tbls doc`.

**Comment by ykostsik** [comment]
Thanks for clearing it up.
