### ISSUE TITLE
Better handling of table descriptions on README vs. detail page.

### ISSUE THREAD

**Issue by mjpieters** [k1LoW/tbls#211]
Currently, the `README.md` file lists all tables with their full table comment.

I'm putting a lot of info in some of my table descriptions, including SQL code blocks. These render rather badly in the *comment* column of the central *Tables* table, which treats markdown just a little different.

Perhaps the *Tables* table should only use the *first paragraph* of each table description.

E.g. the description

> Foo widgets
>
> Tracks Foo widget metadata as the frobnar twiddles with the status and inserts more
> information.
>
> Because there may be redundant, duplicated rows with different timestamps in this table,
> please use a window query to consolidate adjacent rows:
>
> ```sql
> -- Some elaborate sample query
> ```

would only take the text up to the first double newline and so the comment in the *Tables* comments column becomes:

> Foo widgets

and only the detail page shows the remainder.

**Comment by k1LoW** [comment]
Hi @mjpieters.
I know it's very late, but I implemented it in #325 .

Thank you!

**Comment by awa5114** [comment]
@mjpieters I'm curious to know how you were including so much information in your table comments. I too would like to get quite elaborate with table as well as column descriptions. The current suggested workflow with a singular `tbls.yml` is not very practical as it requires the inclusion of the actual markdown of the description in a YAML format. Mind providing any hints on how you achieved this please?

**Comment by mjpieters** [comment]
The project I used this used a mix of `COMMENT` statements and Markdown embedded in the tbls YAML file. We found YAML to be well suited for embedding Markdown, just pick a [multiline style that suits you](https://yaml-multiline.info/).
