### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by KyouQQ** [k1LoW/tbls#251]
### What happened

after I tried to use `tbls doc` with postgre, the error occurred.
<img width="820" alt="截屏2020-08-11 23 45 11" src="https://user-images.githubusercontent.com/69157011/89912045-15774b00-dc2d-11ea-9768-729b7bc02def.png">

### What you expected to happed

get this fixed.

### What stacktrace or error message from tbls did you see?

here it is:

`tbls doc`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41b8fb2]

goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/k1low/.anyenv/envs/goenv/versions/1.13.10/src/database/sql/sql.go:3063 +0x72
database/sql.(*Rows).Close(0x0, 0x5109c4c, 0x3d0)
	/Users/k1low/.anyenv/envs/goenv/versions/1.13.10/src/database/sql/sql.go:3059 +0x33
github.com/k1LoW/tbls/drivers/postgres.(*Postgres).Analyze(0xc00039da80, 0xc000377570, 0x5399d20, 0xc000449ee0)
	/Users/k1low/src/github.com/k1LoW/tbls/drivers/postgres/postgres.go:141 +0x28bb
github.com/k1LoW/tbls/datasource.Analyze(0xc000036640, 0x49, 0x0, 0x0, 0x0, 0x0)
	/Users/k1low/src/github.com/k1LoW/tbls/datasource/datasource.go:111 +0x80b
github.com/k1LoW/tbls/cmd.glob..func5(0x5cfd1e0, 0x5d7c5a8, 0x0, 0x0)
	/Users/k1low/src/github.com/k1LoW/tbls/cmd/doc.go:73 +0x1b0
github.com/spf13/cobra.(*Command).execute(0x5cfd1e0, 0x5d7c5a8, 0x0, 0x0, 0x5cfd1e0, 0x5d7c5a8)
	/Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x5cfd9c0, 0x4, 0x5d7c5a8, 0x0)
	/Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:887
github.com/k1LoW/tbls/cmd.Execute()
	/Users/k1low/src/github.com/k1LoW/tbls/cmd/root.go:184 +0x86
main.main()
	/Users/k1low/src/github.com/k1LoW/tbls/main.go:33 +0x20

### Anything else we need to know?
I get the same error when using other postgresql databases.

### Environment

- `tbls version`
1.43.0

- Database version
psql (PostgreSQL) 9.2.24

- OS 
`macOS Calalina`

- Shell 
`zsh`

- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
`DEBUG=1 tbls doc`
and the same error message.

- Config ( .tbls.yml )
dsn: postgres://user:pw@host:5432/db?sslmode=disable

**Comment by KyouQQ** [comment]
@k1LoW 
I made a same database in `psql (PostgreSQL) 11.8` and  `tbls doc` worked well with the new one, no error happened.
But I'm not sure which postgre version would meet the problem.
Hope this can make help.

**Comment by k1LoW** [comment]
@KyouQQ Thank you for your report!

It appears that tbls is currently unable to support PostgreSQL 9.2 because tbls uses array_remove() (=> PostgreSQL 9.3) in its source code.

I will consider whether this issue can be addressed.

**Comment by k1LoW** [comment]
Released as v1.43.1.
