### ISSUE TITLE
MSSQL: Encountered "Not found table" error when using custom database schema

### ISSUE THREAD

**Issue by el2iot2** [k1LoW/tbls#254]
Thanks for this very interesting work/project. It checks many of the right boxes for my ER-Diagram needs (including CI pipeline and markdown generation features). Further, it works as expected for conventional databases that use the default "dbo" schema for tables.

### What happened
Was able to successfully connect to a Microsoft SQL server, but the first table in the database failed with the error:
"Not found table '{TableNameHere}'"

### What you expected to happed
I expected that the database documentation would be generated.

### Anything else we need to know?

The missing table makes use of a custom database namespace other than "dbo" (e.g.  "appname_dbo"). It seems reasonable that I would need to indicate a database schema configuration when custom, but I don't know if/how to do that. The source code seems to mention "dbo" by name, but it is unclear to me if I can change the `defaultSchemaName` via the `tbls.yml` file.

### Environment

- `tbls version`
1.43.1
- Database version
MSSQL 2016
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
Windows x64
- Shell ( `bash`, `zsh`, `poworshell`, etc )
powershell
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
```
github.com/k1LoW/tbls/schema.(*Schema).FindTableByName

         /Users/k1low/src/github.com/k1LoW/tbls/schema/schema.go:139

 github.com/k1LoW/tbls/drivers/mssql.(*Mssql).Analyze

         /Users/k1low/src/github.com/k1LoW/tbls/drivers/mssql/mssql.go:423

 github.com/k1LoW/tbls/datasource.Analyze

         /Users/k1low/src/github.com/k1LoW/tbls/datasource/datasource.go:111

 github.com/k1LoW/tbls/cmd.glob..func5

         /Users/k1low/src/github.com/k1LoW/tbls/cmd/doc.go:73

 github.com/spf13/cobra.(*Command).execute

         /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:846

 github.com/spf13/cobra.(*Command).ExecuteC

         /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:950

 github.com/spf13/cobra.(*Command).Execute

         /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710123203-207dc47664b4/command.go:887

 github.com/k1LoW/tbls/cmd.Execute

         /Users/k1low/src/github.com/k1LoW/tbls/cmd/root.go:184

 main.main

         /Users/k1low/src/github.com/k1LoW/tbls/main.go:33

 runtime.main

         /usr/local/Cellar/go/1.13.7/libexec/src/runtime/proc.go:203

 runtime.goexit

         /usr/local/Cellar/go/1.13.7/libexec/src/runtime/asm_amd64.s:1357

```
- Config ( .tbls.yml )
```yml
dbn: mssql://un:pwd@hostname:port/dbname
```

**Comment by k1LoW** [comment]
Hi @el2iot2 .

I have updated the sample for MSSQL. Could you check this?

https://github.com/k1LoW/tbls/tree/master/sample/mssql

https://github.com/k1LoW/tbls/blob/8b92450a9f627e21bc9a09868c28e0a2b6fee7a2/testdata/mssql.sql#L139-L149

https://github.com/k1LoW/tbls/blob/8b92450a9f627e21bc9a09868c28e0a2b6fee7a2/testdata/test_tbls_mssql.yml#L67-L69

**Comment by el2iot2** [comment]
I will try this approach (adding a table comment) and see if that gets me past my error. Thanks!

Will I need to do this for every table? They will all have the same custom namespace. Is there a way to set a "default database namespace"?

**Comment by k1LoW** [comment]
> Will I need to do this for every table?

Yes.

> Is there a way to set a "default database namespace"?

Unfortunately, there is no way to do this yet, because the "default schema" is a specification unique to MSSQL and not a concept that exists in other data sources.

**Comment by k1LoW** [comment]
If you can't solve the error, please re-open this Issue again 👍

**Comment by el2iot2** [comment]
So, I finally got back around to trying this. Still getting some strange results. 

From a new/empty setup, adding a comment for a table name did not work. I then used:
```SQL
ALTER SCHEMA dbo TRANSFER appname_dbo.SomeTable;
```
After all my tables were transferred to `dbo`, it started working (as expected).

Oddly, it continued to work after I then transferred some tables back out again (as you may have done for your example?).

Perhaps there is some caching in the output directory that lets it work.

I think this is reproducible if you use a table with a non-`dbo` namespace and a clean install/no docs directory and a tbls.yml file with a fully qualified comment.

On the other hand, I have a quick and easy way to move tables to/from `dbo` and so am unblocked, but there may still be some issues for new users exclusively using custom db namespaces.

Thanks for your time and consideration.

Thanks!
