### ISSUE TITLE
Format the markdown table notation string

### ISSUE THREAD

**Issue by wate** [k1LoW/tbls#27]
Markdownをそのまま見た場合、テーブルの出力内容が整形されておらず非常に見にくいため、
整形して出力するようにしてほしい

**現在の状態**
```
## Columns

| Name | Type | Default | Nullable | Children | Parents | Comment |
| ---- | ---- | ------- | -------- | -------- | ------- | ------- |
| id | int(11) |  | false |  |  |  |
| name | varchar(10) |  | false |  |  |  |
```

**期待する結果**
```
## Columns

| Name | Type        | Default | Nullable | Children | Parents | Comment |
| ---- | ----------- | ------- | -------- | -------- | ------- | ------- |
| id   | int(11)     |         | false    |          |         |         |
| name | varchar(10) |         | false    |          |         |         |
```

**Comment by k1LoW** [comment]
@wate Thank you for your report!!!!

I do not consider seeing the (raw markdown) output of tlbs as it is.

And, I want to support your request, but I have no idea for multibyte support ( ex. proportional font )
If you are able to resolve this, we would encourage you to send a pull request 👍 

> ありがとうございます！
> こちら対応したいとは思ったのですが、マルチバイト対応（プロポーショナルフォント）について良いアイデアがないので、結局崩れるなら対応しないでレンダリングに任せる感じで考えています。
> あと重要なIssueなので、タイトルだけを英語にしておきますね。

**Comment by wate** [comment]
@k1LoW 返信ありがとうございます。

私自身の考えで言えば、厳密にマルチバイト対応(プロポーショナルフォント)までサポートする必要はないと思います。

というのも、プロポーショナルフォントを使っているか否かという部分に関しては、
Markdownを閲覧するエディタのフォント設定に依存するため、tblsでは対応しようが無いと思っております。

私自身goが扱えないので素人考えの部分もあるとは思いますが、
以下のライブラリを利用すれば、私の要望する部分に関しては満たせるのではないかと思っています。

[ASCII Table Writer](https://github.com/olekukonko/tablewriter)
※上記READMR内の「Example 5 - Markdown Format」の部分

**Comment by k1LoW** [comment]
> Markdownを閲覧するエディタのフォント設定に依存するため、tblsでは対応しようが無いと思っております。

そうなのです。なので、今のところ「結局ズレてしまうのならば無理に幅を対応させても。」というのが、私が今積極的でない理由です 🙇

**Comment by k1LoW** [comment]
@wate 
you can use `--adjust-table` ( `-j` ) option from tbls v0.10.0

**Comment by wate** [comment]
@k1LoW 
d(￣◇￣)b ｸﾞｯ♪
