### ISSUE TITLE
MySQL: Inconsistent docs generation if AUTO_INCREMENT has been used

### ISSUE THREAD

**Issue by folago** [k1LoW/tbls#273]
### What happened

Generating the docs with a clean DB or with a DB that has some data gives different results, specifically in tables with AUTO_INCREMENT.

The following diff is form a docs generate from a clean/empty DB and vs. docs generated from a DB with data.

```diff
- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
+ ) ENGINE=InnoDB AUTO_INCREMENT=[Redacted by tbls] DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

### What you expected to happed

No difference in the generated docs regardless of the state of the DB.

### Anything else we need to know?

Would be nice to have a flag to prevent the ` AUTO_INCREMENT=[...]` to be shown, on the same line of #240.

More than happy to send  a PR!

### Environment

- `tbls version`: 1.44.0
- Database version: MySQL 8.0.21
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc ): Linux 
- Shell ( `bash`, `zsh`, `poworshell`, etc )
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
- Config ( .tbls.yml )

**Comment by k1LoW** [comment]
Hi @folago thank you for your report!

I add `hide_auto_increment` option to hide AUTO_INCREMENT clause.

Add `hide_auto_increment` to your DSN as a query option as follows

```
my://myuser:mypass@mylhost:3306/yourdb?hide_auto_increment
```

**Comment by folago** [comment]
Hey @k1LoW,
thanks a lot for the quick fix, works like a charm!
