### ISSUE TITLE
doc command exits with error `malformed version`

### ISSUE THREAD

**Issue by ozzym1096** [k1LoW/tbls#278]
### What happened
When executing `tbls doc` on a PostgreSQL database the program stops and outputs error `malformed version: 12.3,`

### What you expected to happed
doc program should complete and show output filename

### Anything else we need to know?
The PostgreSQL version that tbls obtains has the comma appended for some reason. I'm pretty sure the error might be with the go `database/sql` package, but in any case this might be resolved by slicing off the comma from the string returned at https://github.com/k1LoW/tbls/blob/master/drivers/postgres/postgres.go#L348.

### Environment
- tbls version: `1.48.0`
- Database version: `PostgreSQL 12.3`
- Shell: `powershell`

**Comment by k1LoW** [comment]
Hi @ozzym1096!! Thank you for your report!!
I'll fix it!!!

**Comment by k1LoW** [comment]
Released as v1.48.1.

**Comment by ozzym1096** [comment]
Nice! Thanks for the quick patch 👍
