### ISSUE TITLE
Way to update the documentation

### ISSUE THREAD

**Issue by tomi** [k1LoW/tbls#286]
Hi and first of all thank you for this great tool! It is precisely what I've been looking for.

During development after I've done the schema changes, what is the correct workflow to update the documentation during development? If I run `tbls doc` it says

> output files already exists

`tbls diff` does show the diff, but how do I apply the diff? I could first remove the old documentation and the generate it again, but it would be nice to have a way to do that with a single command. For example `tbls doc --update`. What do you think?

**Comment by k1LoW** [comment]
Hi @tomi.

You can use `--force` option for override files or `--rm-dist` option for removing files in docPath before generating documents.

**Comment by tomi** [comment]
Cool, thank you! 🙏  I created a PR about mentioning this in the README so others can find it too https://github.com/k1LoW/tbls/pull/287
