### ISSUE TITLE
Tbls crashes 

### ISSUE THREAD

**Issue by svservices** [k1LoW/tbls#288]
### What happened
tbls crashed

### What you expected to happed
Generate doc
### What stacktrace or error message from tbls did you see?

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/k1LoW/tbls/drivers/mysql.(*Mysql).Analyze(0xc00089ce50, 0xc0000297a0, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/drivers/mysql/mysql.go:421 +0x4876
github.com/k1LoW/tbls/datasource.Analyze(0xc0008b5c00, 0x33, 0x0, 0x0, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/datasource/datasource.go:114 +0xba8
github.com/k1LoW/tbls/cmd.glob..func5(0x2132420, 0x225b488, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/doc.go:73 +0x1a5
github.com/spf13/cobra.(*Command).execute(0x2132420, 0x225b488, 0x0, 0x0, 0x2132420, 0x225b488)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2132c00, 0x4, 0x225b488, 0x0)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/k1LoW/tbls/cmd.Execute()
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/root.go:187 +0x86
main.main()
        /Users/k1low/src/github.com/k1LoW/tbls/main.go:34 +0x25

### Anything else we need to know?
 No
### Environment
 `tbls version`:  1.49.2
Database version: Mariadb 10.4.17
OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc ):  WSL2 ubuntu, i tried also docker, same issue
Shell ( `bash`, `zsh`, `poworshell`, etc ): bash
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/k1LoW/tbls/drivers/mysql.(*Mysql).Analyze(0xc00089ce50, 0xc0000297a0, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/drivers/mysql/mysql.go:421 +0x4876
github.com/k1LoW/tbls/datasource.Analyze(0xc0008b5c00, 0x33, 0x0, 0x0, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/datasource/datasource.go:114 +0xba8
github.com/k1LoW/tbls/cmd.glob..func5(0x2132420, 0x225b488, 0x0, 0x0)
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/doc.go:73 +0x1a5
github.com/spf13/cobra.(*Command).execute(0x2132420, 0x225b488, 0x0, 0x0, 0x2132420, 0x225b488)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2132c00, 0x4, 0x225b488, 0x0)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/k1low/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/k1LoW/tbls/cmd.Execute()
        /Users/k1low/src/github.com/k1LoW/tbls/cmd/root.go:187 +0x86
main.main()
        /Users/k1low/src/github.com/k1LoW/tbls/main.go:34 +0x25
 Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
Config ( .tbls.yml ): 
dsn: mariadb://root:xxxxxxxxxxxxx@192.16.47.51:3306/warehouse
docPath: doc/schema

**Comment by svservices** [comment]
I tried another database and it work but not for the one I need :( .

**Comment by k1LoW** [comment]
@svservices  Thank you for your report!

I can't find the cause from the stack trace at the moment, but I will try to implement to output a log that shows the cause at first.

**Comment by svservices** [comment]
The database i try to document is quite complex, 330 tables, some tables have lots of columns (30,50 even 130), lots of foreign keys and indexes. If I can help you with something let me know.

**Comment by k1LoW** [comment]
@svservices 

v1.49.3 released.

If you don't mind, can you run `tbls doc` again using v1.49.3 to get the stacktrace?

**Comment by svservices** [comment]
I run it: 

**can not parse foreign key: FOREIGN KEY (location_id, id) REFERENCES  ()**
I'm looking over database structure to detect the table.

**Comment by k1LoW** [comment]
> REFERENCES ()

🤔 fmm...  I see that tbls is failing to get the information about the foreign key reference...

**Comment by k1LoW** [comment]
> I'm looking over database structure to detect the table.

You may be able to find the table with the following query.

```sql
SELECT * FROM (
SELECT
  kcu.constraint_name,
  sub.costraint_type,
  GROUP_CONCAT(kcu.column_name ORDER BY kcu.ordinal_position, position_in_unique_constraint SEPARATOR ', ') AS column_name,
  kcu.referenced_table_name,
  GROUP_CONCAT(kcu.referenced_column_name ORDER BY kcu.ordinal_position, position_in_unique_constraint SEPARATOR ', ') AS referenced_column_name
FROM information_schema.key_column_usage AS kcu
LEFT JOIN information_schema.columns AS c ON kcu.table_schema = c.table_schema AND kcu.table_name = c.table_name AND kcu.column_name = c.column_name
LEFT JOIN
  (
   SELECT
   kcu.table_schema,
   kcu.table_name,
   kcu.constraint_name,
   kcu.column_name,
   (CASE WHEN kcu.referenced_table_name IS NOT NULL THEN 'FOREIGN KEY'
        WHEN c.column_key = 'PRI' AND kcu.constraint_name = 'PRIMARY' THEN 'PRIMARY KEY'
        WHEN c.column_key = 'PRI' AND kcu.constraint_name != 'PRIMARY' THEN 'UNIQUE'
        WHEN c.column_key = 'UNI' THEN 'UNIQUE'
        WHEN c.column_key = 'MUL' THEN 'UNIQUE'
        ELSE 'UNKNOWN'
   END) AS costraint_type
   FROM information_schema.key_column_usage AS kcu
   LEFT JOIN information_schema.columns AS c ON kcu.table_schema = c.table_schema AND kcu.table_name = c.table_name AND kcu.column_name = c.column_name
   AND kcu.ordinal_position = 1
  ) AS sub
ON kcu.constraint_name = sub.constraint_name AND kcu.table_schema = sub.table_schema AND kcu.table_name = sub.table_name
GROUP BY kcu.constraint_name, sub.costraint_type, kcu.referenced_table_name
) AS a
WHERE column_name = 'location_id, id'
```

**Comment by svservices** [comment]
> > I'm looking over database structure to detect the table.
> 
> You may be able to find the table with the following query.
> 
> ```sql
> SELECT * FROM (
> SELECT
>   kcu.constraint_name,
>   sub.costraint_type,
>   GROUP_CONCAT(kcu.column_name ORDER BY kcu.ordinal_position, position_in_unique_constraint SEPARATOR ', ') AS column_name,
>   kcu.referenced_table_name,
>   GROUP_CONCAT(kcu.referenced_column_name ORDER BY kcu.ordinal_position, position_in_unique_constraint SEPARATOR ', ') AS referenced_column_name
> FROM information_schema.key_column_usage AS kcu
> LEFT JOIN information_schema.columns AS c ON kcu.table_schema = c.table_schema AND kcu.table_name = c.table_name AND kcu.column_name = c.column_name
> LEFT JOIN
>   (
>    SELECT
>    kcu.table_schema,
>    kcu.table_name,
>    kcu.constraint_name,
>    kcu.column_name,
>    (CASE WHEN kcu.referenced_table_name IS NOT NULL THEN 'FOREIGN KEY'
>         WHEN c.column_key = 'PRI' AND kcu.constraint_name = 'PRIMARY' THEN 'PRIMARY KEY'
>         WHEN c.column_key = 'PRI' AND kcu.constraint_name != 'PRIMARY' THEN 'UNIQUE'
>         WHEN c.column_key = 'UNI' THEN 'UNIQUE'
>         WHEN c.column_key = 'MUL' THEN 'UNIQUE'
>         ELSE 'UNKNOWN'
>    END) AS costraint_type
>    FROM information_schema.key_column_usage AS kcu
>    LEFT JOIN information_schema.columns AS c ON kcu.table_schema = c.table_schema AND kcu.table_name = c.table_name AND kcu.column_name = c.column_name
>    AND kcu.ordinal_position = 1
>   ) AS sub
> ON kcu.constraint_name = sub.constraint_name AND kcu.table_schema = sub.table_schema AND kcu.table_name = sub.table_name
> GROUP BY kcu.constraint_name, sub.costraint_type, kcu.referenced_table_name
> ) AS a
> WHERE column_name = 'location_id, id'
> ```

+-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
| constraint_name         | costraint_type | column_name     | referenced_table_name | referenced_column_name                                              |
+-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
| gift_action_location_id | FOREIGN KEY    | location_id, id | NULL                  | NULL                                                                |
| gift_action_location_id | UNIQUE         | location_id, id | NULL                  | NULL                                                                |
| gift_action_location_id | UNKNOWN        | location_id, id | NULL                  | NULL                                                                |
+-------------------------+----------------+-----------------+-----------------------+------------------------

**Comment by svservices** [comment]
```
+-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
| constraint_name         | costraint_type | column_name     | referenced_table_name | referenced_column_name                                              |
+-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
| gift_action_location_id | FOREIGN KEY    | location_id, id | NULL                  | NULL                                                                |
| gift_action_location_id | UNIQUE         | location_id, id | NULL                  | NULL                                                                |
| gift_action_location_id | UNKNOWN        | location_id, id | NULL                  | NULL                                                                |
+-------------------------+----------------+-----------------+-----------------------+------------------------                               
```

**Comment by svservices** [comment]
> Based on your query i found this.
> 
> ```
> +-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
> | constraint_name         | costraint_type | column_name     | referenced_table_name | referenced_column_name                                              |
> +-------------------------+----------------+-----------------+-----------------------+------------------------                                             +
> | gift_action_location_id | FOREIGN KEY    | location_id, id | NULL                  | NULL                                                                |
> | gift_action_location_id | UNIQUE         | location_id, id | NULL                  | NULL                                                                |
> | gift_action_location_id | UNKNOWN        | location_id, id | NULL                  | NULL                                                                |
> +-------------------------+----------------+-----------------+-----------------------+------------------------                               
> ```

In table structure i see only this as contraint:
`CONSTRAINT `gift_action_location_id` FOREIGN KEY (`location_id`) REFERENCES `gift_location` (`id`),`

and a unique key with the same name
`UNIQUE KEY `gift_action_location_id` (`location_id`,`id`),`

**Comment by svservices** [comment]
If I drop the foreign key constraint gift_action_location_id and recreate with another name , for ex. gift_action_location_id_fk, tbls it works.

**Comment by k1LoW** [comment]
@svservices Thank you !!!
This is bug. I'll fix it.

**Comment by k1LoW** [comment]
In MySQL, it is not possible to have the same constraint name on the same table (1061: Duplicate key name), but in MariaDB, it is possible.

**Comment by k1LoW** [comment]
v1.49.4 released.

Can you try the `tbls doc` again?

**Comment by svservices** [comment]
It works now.
Thanks.

**Comment by k1LoW** [comment]
👍 
Thank you for your report!!!
