### ISSUE TITLE
Generate documentation from .sql files.

### ISSUE THREAD

**Issue by navaneeth-spotnana** [k1LoW/tbls#289]
I have a set of .sql files. Can I supply it to tbls somehow and generate the documentation? 

I want to support .sql files as input. Is this possible? If not, do you have ideas on how to get around this?

Thanks for this neat and extremely useful project! ❤️

**Comment by k1LoW** [comment]
@navaneeth-spotnana Thank you for your request.

> do you have ideas on how to get around this?

If you run SQL into a database on a Docker container and generate the documentation with `tbls doc`, you can achieve what you wanted.
