### ISSUE TITLE
Support configuration for multiple database

### ISSUE THREAD

**Issue by navaneeth-spotnana** [k1LoW/tbls#290]
Multiple DBs are frequent, especially in a microservice environment. Can we configure multiple DBs in .tbls.yml?

Related to #127

**Comment by k1LoW** [comment]
> Can we configure multiple DBs in .tbls.yml?

Unfortunately, tbls does not support multiple databases in a single configuration file

**Comment by koolay** [comment]
@k1LoW  Why not support multiple database ?

**Comment by k1LoW** [comment]
This is because if we want to document two databases, we only need to prepare two configuration files.

I think there is no need to further complexify the .tbls.yml, which even now can be huge.
