### ISSUE TITLE
Add additional information for postgress

### ISSUE THREAD

**Issue by muhfaris** [k1LoW/tbls#300]
I thought adding more information on connection PostgreSQL is better.
when using SSL mode the config like below :
```
# DSN (Database Source Name) to connect database
dsn: postgres://dbuser:dbpass@localhost:5432/dbname?sslmode=disable
```
or
```
# DSN (Database Source Name) to connect database
dsn: postgres://dbuser:dbpass@localhost:5432/dbname?sslmode=verify-full&sslrootcert=ca-cert.pem
```

some available sslmode of postgresql : disable, allow, prefer, require, verify-ca, verify-full

**Comment by YauhenPylAurea** [comment]
it feels like this issue should be closed ...
