### ISSUE TITLE
Bug: tbls thinks password is port if password contains # (hash) in it

### ISSUE THREAD

**Issue by kpldvnpne** [k1LoW/tbls#348]
### What happened
When I try to do:
```bash
tbls doc postgres://user:pass#word@host:5432/dbname
```
`tbls` seems to think that `user` is host and `pass` is port. Then, it fails saying `pass` is not a valid port.

### What you expected to happened
I expected it to treat `user` as user and `pass#word` as password. And then I expected it to create the document properly.

### What stack trace or error message from tbls did you see?
```bash
parse "postgres://user:pass": invalid port ":pass" after host
```

### Anything else we need to know?
No

### Environment

- `tbls version` : 1.55.1
- Database version : postgresql
- OS: `Amazon Linux 2`
- Shell: `bash`
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`):  `parse "postgres://user:pass": invalid port ":pass" after host`
- Config: **Not used**

**Comment by k1LoW** [comment]
Hi.

If you are using a symbol such as `#` `<` in database password, URL-encode the password.

ref: https://github.com/k1LoW/tbls#document-a-database

**Comment by kpldvnpne** [comment]
Thanks. Stupid of me to not notice it in the README. I will close the thread

**Comment by k1LoW** [comment]
Thanks for using tbls!
