### ISSUE TITLE
Support for custom types / enums

### ISSUE THREAD

**Issue by lorefnon** [k1LoW/tbls#357]
It would be good if tbls could also generate docs for custom types esp. enums for which we often want to lookup all permitted values. 

I am also [using](https://github.com/lorefnon/ts-sql-codegen) the generated yaml schema for code-generation and having the enum values available will enable me to translate those to generated types.

**Comment by fira42073** [comment]
I believe this could be closed?

**Comment by lorefnon** [comment]
Oh this was added in. Great. Thank you.
