### ISSUE TITLE
Docker - Unable to connect to Snowflake due to x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by awhitford-cip** [k1LoW/tbls#378]
### What happened

When running docker image ghcr.io/k1low/tbls from a GitHub Action, it is no longer able to connect to Snowflake.  This is the error:

> Post "https://zX12345.east-us-2.azure.snowflakecomputing.com:443/session/v1/login-request?databaseName=DB_CI_3&requestId=dbb7115c-5b98-401e-a26b-1e9ff3f8c9f6&request_guid=2e3e608b-43ec-41f6-b0b8-40812ed74b79&schemaName=PUBLIC": x509: certificate signed by unknown authority

### What you expected to happened

I would expect `tbls` to connect successfully to the Snowflake database.  This was working up until the most recent release.

### What stack trace or error message from tbls did you see?

> Post "https://zX12345.east-us-2.azure.snowflakecomputing.com:443/session/v1/login-request?databaseName=DB_CI_3&requestId=dbb7115c-5b98-401e-a26b-1e9ff3f8c9f6&request_guid=2e3e608b-43ec-41f6-b0b8-40812ed74b79&schemaName=PUBLIC": x509: certificate signed by unknown authority

### Anything else we need to know?

Rolling back to version 1.56.3 restores functionality.

I think this is related to PR #375; specifically the `Dockerfile` change:
 * https://github.com/k1LoW/tbls/pull/375/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc

This StackOverflow article likely explains the solution:
* https://stackoverflow.com/questions/67825629/error-x509-certificate-signed-by-unknown-authority-while-connecting-to-snowfl

### Environment

- `tbls version`:  **1.56.5**
- Database version:  **Snowflake**
- OS:  `ubuntu-latest` -- from _GitHub Actions_
- Shell ( `bash`, `zsh`, `poworshell`, etc ) -- `Docker`

**Comment by k1LoW** [comment]
@awhitford-cip Thank you for your report!

**Comment by k1LoW** [comment]
@awhitford-cip Released as v1.56.6. Could you check when you have time?

**Comment by awhitford-cip** [comment]
Yes, it seems to be working now.  Thank you for resolving quickly!
