### ISSUE TITLE
Library version? Can I import tbls as a lib then print info as my http service is running?

### ISSUE THREAD

**Issue by haunt98** [k1LoW/tbls#381]
For example, I have a Go HTTP service,
I want each time my service starts, it output data generate from tbls.
Is it possible?

**Comment by k1LoW** [comment]
Although tbls is not designed to be embedded as a library, I think it is possible, depending on how it is done.

Read the code and you be the judge 👍

**Comment by k1LoW** [comment]
The entry point for tbls as the CLI tool is [here](https://github.com/k1LoW/tbls/blob/main/main.go#L34).

We could say that the github.com/k1LoW/tbls/cmd package uses the github.com/k1LoW/tbls package as a library.

**Comment by haunt98** [comment]
Seems good for a start, I will close issue for now :) Thank you for guiding
