### ISSUE TITLE
Percentage columns are always output in Excel format

### ISSUE THREAD

**Issue by zonbitamago** [k1LoW/tbls#388]
### What happened
Percentage columns are always output in Excel format
<img width="571" alt="issue" src="https://user-images.githubusercontent.com/30372332/204784423-d74896f8-f217-4d5d-ac87-c4706cc44af5.png">

### What you expected to happened
Percentage columns are not output by default in excel format
<img width="571" alt="fixed" src="https://user-images.githubusercontent.com/30372332/204784863-5f85f230-2b24-4f98-9596-cb685cf3d0ba.png">

### What stack trace or error message from tbls did you see?
nothing

### Anything else we need to know?
Perhaps, the `Percent` below is incorrect.
(I think, this is simple typo mistake)

Error: `Percent`
Correct: `Percents`
https://github.com/k1LoW/tbls/blob/d90f7ab181f97abf46371f0048aa1e2e07cf9434/output/xlsx/xlsx.go#L191

### Environment

- `tbls version`
  - 1.56.8
- Database version
  - postgresql:15
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
  - macOS Ventura
- Shell ( `bash`, `zsh`, `poworshell`, etc )
  - `zsh`
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
  - nothing
- Config ( .tbls.yml )
  - nothing

**Comment by k1LoW** [comment]
@zonbitamago Thank you for your report!!
