### ISSUE TITLE
How to create table from schema doc automatically

### ISSUE THREAD

**Issue by yeongjet** [k1LoW/tbls#401]
I cloned the new project(which has full table schema doc) to local , but I don't have these tables yet，how to create them automatically.

**Comment by k1LoW** [comment]
Can you send me some more information? I am still trying to understand what you want.

---

### What happened

### What you expected to happened

### What stack trace or error message from tbls did you see?

### Anything else we need to know?

### Environment

- `tbls version`
- Database version
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
- Shell ( `bash`, `zsh`, `poworshell`, etc )
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
- Config ( .tbls.yml )

**Comment by sprak3000** [comment]
@k1LoW 

It sounds like they are looking for a way to use existing database documentation to generate the actual tables in their database. I don't believe `tbls` supports this.

**Comment by k1LoW** [comment]
> a way to use existing database documentation to generate the actual tables in their database. 

Certainly tbls does not support it.

```

**Comment by yeongjet** [comment]
@sprak3000 Yes, this is what I mean.
