### ISSUE TITLE
Encoding wrong when executing with powershell or cmd

### ISSUE THREAD

**Issue by cocoonkid** [k1LoW/tbls#449]
### What happened

![image](https://user-images.githubusercontent.com/43231640/224325483-6a7033dc-9144-41db-9e9d-459d76d07a1e.png)

### What you expected to happened

Correct encoding utf-8 not html

### Anything else we need to know?

when generating a svg it works but not for mermaid diagrams.

### Environment

Windows 10 powershell or cmd.  

I hope I worded everything properly.

Feel free to correct my post at all times ;-)

**Comment by k1LoW** [comment]
@cocoonkid Thank you for your report!
