### ISSUE TITLE
Viewpoints from tables not refered just in `diff`

### ISSUE THREAD

**Issue by macoto1995** [k1LoW/tbls#535]
### What happened
Viewpoints section in tables markdown is not generated when I run tbls diff, even after I run `tbls doc`

### What you expected to happened
`tbls diff` command generate Viewpoints section internally.

### What stack trace or error message from tbls did you see?
No errors

### Anything else we need to know?
Viewpoints section is not set because the line I added last PR below
https://github.com/macoto1995/tbls/blob/693d890545dbeaaa261260b976d6d298ef6e3af7/output/md/md.go#L132

is not applied to diff (DiffSchemas?)
https://github.com/macoto1995/tbls/blob/693d890545dbeaaa261260b976d6d298ef6e3af7/output/md/md.go#L209

### Environment

- `tbls version`
1.71.0
- Database version
- OS ( `Ubuntu bionic`, `macOS Calalina`, `WSL2`, etc )
- Shell ( `bash`, `zsh`, `poworshell`, etc )
- Stacktrace or error message from tbls ( If you can, set `DEBUG=1`)
- Config ( .tbls.yml )

**Comment by k1LoW** [comment]
@macoto1995 
Thank you for your report!
