### ISSUE TITLE
An error about：invalid database scheme

### ISSUE THREAD

**Issue by AlilyZ** [k1LoW/tbls#560]
I followed the method in the readme, used go to download the latest version of tbls.
And used the method provided in the readme to configure the yml file for connecting to MySQL.
As follows: 
# .tbls.yml
dsn: mysql://root:root@127.0.0.1:3306/test

Then I opened cmd in the bin directory of tbls, and executed D:\bin>tbls doc -c tbls.yml -f erd.
The error is as follows : invalid database scheme

Using the navicat tool can connect to mysql 127.0.0.1:3306/test 
How should I handle it？

**Comment by k1LoW** [comment]
Hi @AlilyZ 

Please show me the result of each of the following commands.

```console
$ env DEBUG=1 tbls doc mysql://root:root@127.0.0.1:3306/test
```

```console
$ env DEBUG=1 tbls doc -c tbls.yml -f erd
```

**Comment by AlilyZ** [comment]
Thank you very much for your reply. The results of these two commands are as follows：
D:\go\bin\bin>tbls doc mysql://root:root@127.0.0.1:3306/test
dbdoc\schema.svg
dbdoc\class.svg
dbdoc\relative.svg
dbdoc\students.svg
dbdoc\README.md
dbdoc\class.md
dbdoc\relative.md
dbdoc\students.md
dbdoc\schema.json

D:\go\bin\bin>tbls doc -c tbls.yml -f erd
invalid database scheme

**Comment by AlilyZ** [comment]
> Thank you very much for your reply. The results of these two commands are as follows： D:\go\bin\bin>tbls doc mysql://root:root@127.0.0.1:3306/test dbdoc\schema.svg dbdoc\class.svg dbdoc\relative.svg dbdoc\students.svg dbdoc\README.md dbdoc\class.md dbdoc\relative.md dbdoc\students.md dbdoc\schema.json
> 
> D:\go\bin\bin>tbls doc -c tbls.yml -f erd invalid database scheme

Thank you very much for your reply. The results of these two commands are as follows：
D:\go\bin\bin>tbls doc mysql://root:root@127.0.0.1:3306/test
dbdoc\schema.svg
dbdoc\class.svg
dbdoc\relative.svg
dbdoc\students.svg
dbdoc\README.md
dbdoc\class.md
dbdoc\relative.md
dbdoc\students.md
dbdoc\schema.json

D:\go\bin\bin>tbls doc -c tbls.yml -f erd
invalid database scheme

**Comment by k1LoW** [comment]
Could you run some commands as follows?

```console
$ tbls version
1.73.2
$ cat .tbls.yml
dsn: mysql://root:mypass@localhost:33308/testdb
$ tbls doc -c .tbls.yml
dbdoc/schema.svg
dbdoc/CamelizeTable.svg
dbdoc/comment_stars.svg
dbdoc/comments.svg
dbdoc/hyphen-table.svg
dbdoc/logs.svg
dbdoc/long_long_long_long_long_long_long_long_table_name.svg
dbdoc/post_comments.svg
dbdoc/posts.svg
dbdoc/user_options.svg
dbdoc/users.svg
dbdoc/README.md
dbdoc/CamelizeTable.md
dbdoc/comment_stars.md
dbdoc/comments.md
dbdoc/hyphen-table.md
dbdoc/logs.md
dbdoc/long_long_long_long_long_long_long_long_table_name.md
dbdoc/post_comments.md
dbdoc/posts.md
dbdoc/user_options.md
dbdoc/users.md
dbdoc/schema.json
~/src/github.com/k1LoW/tbls (main)>
```

**Comment by AlilyZ** [comment]
> Could you run some commands as follows?
> 
> ( I'm a little concerned about the syntax of the config file. )
> 
> ```
> $ tbls version
> 1.73.2
> $ cat .tbls.yml
> dsn: mysql://root:mypass@localhost:33308/testdb
> $ tbls doc -c .tbls.yml
> dbdoc/schema.svg
> dbdoc/CamelizeTable.svg
> dbdoc/comment_stars.svg
> dbdoc/comments.svg
> dbdoc/hyphen-table.svg
> dbdoc/logs.svg
> dbdoc/long_long_long_long_long_long_long_long_table_name.svg
> dbdoc/post_comments.svg
> dbdoc/posts.svg
> dbdoc/user_options.svg
> dbdoc/users.svg
> dbdoc/README.md
> dbdoc/CamelizeTable.md
> dbdoc/comment_stars.md
> dbdoc/comments.md
> dbdoc/hyphen-table.md
> dbdoc/logs.md
> dbdoc/long_long_long_long_long_long_long_long_table_name.md
> dbdoc/post_comments.md
> dbdoc/posts.md
> dbdoc/user_options.md
> dbdoc/users.md
> dbdoc/schema.json
> $
> ```



> Could you run some commands as follows?
> 
> ( I'm a little concerned about the syntax of the config file. )
> 
> ```
> $ tbls version
> 1.73.2
> $ cat .tbls.yml
> dsn: mysql://root:mypass@localhost:33308/testdb
> $ tbls doc -c .tbls.yml
> dbdoc/schema.svg
> dbdoc/CamelizeTable.svg
> dbdoc/comment_stars.svg
> dbdoc/comments.svg
> dbdoc/hyphen-table.svg
> dbdoc/logs.svg
> dbdoc/long_long_long_long_long_long_long_long_table_name.svg
> dbdoc/post_comments.svg
> dbdoc/posts.svg
> dbdoc/user_options.svg
> dbdoc/users.svg
> dbdoc/README.md
> dbdoc/CamelizeTable.md
> dbdoc/comment_stars.md
> dbdoc/comments.md
> dbdoc/hyphen-table.md
> dbdoc/logs.md
> dbdoc/long_long_long_long_long_long_long_long_table_name.md
> dbdoc/post_comments.md
> dbdoc/posts.md
> dbdoc/user_options.md
> dbdoc/users.md
> dbdoc/schema.json
> $
> ```



> Could you run some commands as follows?
> 
> ( I'm a little concerned about the syntax of the config file. )
> 
> ```
> $ tbls version
> 1.73.2
> $ cat .tbls.yml
> dsn: mysql://root:mypass@localhost:33308/testdb
> $ tbls doc -c .tbls.yml
> dbdoc/schema.svg
> dbdoc/CamelizeTable.svg
> dbdoc/comment_stars.svg
> dbdoc/comments.svg
> dbdoc/hyphen-table.svg
> dbdoc/logs.svg
> dbdoc/long_long_long_long_long_long_long_long_table_name.svg
> dbdoc/post_comments.svg
> dbdoc/posts.svg
> dbdoc/user_options.svg
> dbdoc/users.svg
> dbdoc/README.md
> dbdoc/CamelizeTable.md
> dbdoc/comment_stars.md
> dbdoc/comments.md
> dbdoc/hyphen-table.md
> dbdoc/logs.md
> dbdoc/long_long_long_long_long_long_long_long_table_name.md
> dbdoc/post_comments.md
> dbdoc/posts.md
> dbdoc/user_options.md
> dbdoc/users.md
> dbdoc/schema.json
> $
> ```

![20240218142320](https://github.com/k1LoW/tbls/assets/159122110/359cc348-758c-45a0-aace-afa1c31fe937)

**Comment by AlilyZ** [comment]
> Could you run some commands as follows?
> 
> ( I'm a little concerned about the syntax of the config file. )
> 
> ```
> $ tbls version
> 1.73.2
> $ cat .tbls.yml
> dsn: mysql://root:mypass@localhost:33308/testdb
> $ tbls doc -c .tbls.yml
> dbdoc/schema.svg
> dbdoc/CamelizeTable.svg
> dbdoc/comment_stars.svg
> dbdoc/comments.svg
> dbdoc/hyphen-table.svg
> dbdoc/logs.svg
> dbdoc/long_long_long_long_long_long_long_long_table_name.svg
> dbdoc/post_comments.svg
> dbdoc/posts.svg
> dbdoc/user_options.svg
> dbdoc/users.svg
> dbdoc/README.md
> dbdoc/CamelizeTable.md
> dbdoc/comment_stars.md
> dbdoc/comments.md
> dbdoc/hyphen-table.md
> dbdoc/logs.md
> dbdoc/long_long_long_long_long_long_long_long_table_name.md
> dbdoc/post_comments.md
> dbdoc/posts.md
> dbdoc/user_options.md
> dbdoc/users.md
> dbdoc/schema.json
> $
> ```


D:\go\bin\bin>tbls doc -c tbls.yml
output ER diagram files already exists

D:\go\bin\bin>tbls version
1.73.2

D:\go\bin\bin>type tbls.yml
dsn: mysql://root:root@127.0.0.1:3306/test




D:\go\bin\bin>tbls doc -c tbls.yml
dbdoc\schema.svg
dbdoc\class.svg
dbdoc\relative.svg
dbdoc\students.svg
dbdoc\README.md
dbdoc\class.md
dbdoc\relative.md
dbdoc\students.md
dbdoc\schema.json

**Comment by AlilyZ** [comment]
> > Could you run some commands as follows?
> > ( I'm a little concerned about the syntax of the config file. )
> > ```
> > $ tbls version
> > 1.73.2
> > $ cat .tbls.yml
> > dsn: mysql://root:mypass@localhost:33308/testdb
> > $ tbls doc -c .tbls.yml
> > dbdoc/schema.svg
> > dbdoc/CamelizeTable.svg
> > dbdoc/comment_stars.svg
> > dbdoc/comments.svg
> > dbdoc/hyphen-table.svg
> > dbdoc/logs.svg
> > dbdoc/long_long_long_long_long_long_long_long_table_name.svg
> > dbdoc/post_comments.svg
> > dbdoc/posts.svg
> > dbdoc/user_options.svg
> > dbdoc/users.svg
> > dbdoc/README.md
> > dbdoc/CamelizeTable.md
> > dbdoc/comment_stars.md
> > dbdoc/comments.md
> > dbdoc/hyphen-table.md
> > dbdoc/logs.md
> > dbdoc/long_long_long_long_long_long_long_long_table_name.md
> > dbdoc/post_comments.md
> > dbdoc/posts.md
> > dbdoc/user_options.md
> > dbdoc/users.md
> > dbdoc/schema.json
> > $
> > ```
> 
> D:\go\bin\bin>tbls doc -c tbls.yml output ER diagram files already exists
> 
> D:\go\bin\bin>tbls version 1.73.2
> 
> D:\go\bin\bin>type tbls.yml dsn: mysql://root:root@127.0.0.1:3306/test
> 
> D:\go\bin\bin>tbls doc -c tbls.yml dbdoc\schema.svg dbdoc\class.svg dbdoc\relative.svg dbdoc\students.svg dbdoc\README.md dbdoc\class.md dbdoc\relative.md dbdoc\students.md dbdoc\schema.json

![20240218142320](https://github.com/k1LoW/tbls/assets/159122110/e49331e9-bc6b-4da3-a77a-e4f59234196a)

**Comment by k1LoW** [comment]
@AlilyZ 

Yeah, I finally understood what you were asking with your answer!

```console
tbls doc -c tbls.yml -f erd.
```

In the case of this command, `erd` is interpreted as a DSN.

Because tbls doc is in the following order when receiving args

```console
tbls doc [DSN] [DOC_PATH]
```

**Comment by AlilyZ** [comment]
> @AlilyZ
> 
> Yeah, I finally understood what you were asking with your answer!
> 
> ```
> tbls doc -c tbls.yml -f erd.
> ```
> 
> In the case of this command, `erd` is interpreted as a DSN.
> 
> Because tbls doc is in the following order when receiving args
> 
> ```
> tbls doc [DSN] [DOC_PATH]
> ```
> 
> Pass DSN and DOC_PATH as arguments or set the path in the `docPath:` section of tbls.yml.

Thank you very much for helping me solve my doubts.

**Comment by AlilyZ** [comment]
> @AlilyZ
> 
> Yeah, I finally understood what you were asking with your answer!
> 
> ```
> tbls doc -c tbls.yml -f erd.
> ```
> 
> In the case of this command, `erd` is interpreted as a DSN.
> 
> Because tbls doc is in the following order when receiving args
> 
> ```
> tbls doc [DSN] [DOC_PATH]
> ```
> 
> Pass DSN and DOC_PATH as arguments or set the path in the `docPath:` section of tbls.yml.

Thank you very much for helping me solve my doubts.

**Comment by AlilyZ** [comment]
> @AlilyZ
> 
> Yeah, I finally understood what you were asking with your answer!
> 
> ```
> tbls doc -c tbls.yml -f erd.
> ```
> 
> In the case of this command, `erd` is interpreted as a DSN.
> 
> Because tbls doc is in the following order when receiving args
> 
> ```
> tbls doc [DSN] [DOC_PATH]
> ```
> 
> Pass DSN and DOC_PATH as arguments or set the path in the `docPath:` section of tbls.yml.

Thank you very much for helping me solve my doubts
