### ISSUE TITLE
Github action could not find a writable bin path: /usr/local/bin:/usr/bin:/bin:/snap/bin

### ISSUE THREAD

**Issue by lionslair** [k1LoW/tbls#562]
### What happened

I am trying to run this on self hosted github actions

### What you expected to happened

The task to run

### What stack trace or error message from tbls did you see?

Error: could not find a writable bin path: /usr/local/bin:/usr/bin:/bin:/snap/bin

![image](https://github.com/k1LoW/tbls/assets/832259/ccfc9de3-628a-469c-8edf-355789bf5fee)

### Environment

- `tbls version`
- Database version
- OS (ubuntu 22.04 on aws ec2)
- Shell ( `bash`,c )

I have ensured at minimum /home/ubuntu/bin is in the PATH variable but this does not seem to use the path no matter what

**Comment by k1LoW** [comment]
> I have ensured at minimum /home/ubuntu/bin is in the PATH variable but this does not seem to use the path no matter what

Is /home/ubuntu/bin in the PATH of the user running setup-tbls?

For example, could you show me the result of the following run?

```yaml
steps:
- run: |
      id
      echo $HOME
      echo $PATH
```

**Comment by lionslair** [comment]
Thanks for the fast reply

```bash

Run id
  id
  echo $HOME
  echo $PATH
  shell: /usr/bin/bash -e {0}
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),119(netdev),120(lxd),998(docker)
/home/ubuntu
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

```

Looks like it is still missing the path

![image](https://github.com/k1LoW/tbls/assets/832259/8bc52e48-4d16-4788-8c5c-da41c5736dd8)

```
ubuntu@ip-10-0-1-21:~$ htop
ubuntu@ip-10-0-1-21:~$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),119(netdev),120(lxd),998(docker)
ubuntu@ip-10-0-1-21:~$ echo $HOME
/home/ubuntu
ubuntu@ip-10-0-1-21:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/bin:/home/ubuntu/.config/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib/npm/bin
ubuntu@ip-10-0-1-21:~$ 

```

**Comment by lionslair** [comment]
It is in the .bashrc

``` bash
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
export BAT_PAGER="never"
PATH="$HOME/bin:$PATH"
```

**Comment by k1LoW** [comment]
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

It is difficult to install using setup-tbls unless the PATH of the user running the job is changed.

**Comment by lionslair** [comment]
> > /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
> 
> It is difficult to install using setup-tbls unless the PATH of the user running the job is changed.
> 
> And that seems to be the problem with self hosted runner.

If I preinstall golang into the image and also run

```bash
go install github.com/k1LoW/tbls@latest
```

should I need to run the setup?

**Comment by k1LoW** [comment]
If the environment and PATH are sufficient for `go install`, it is possible.

**Comment by lionslair** [comment]
Ok I have solved it by adding the .deb to the base image then I do not need to run setup in the action. 

Thanks.
