### ISSUE TITLE
sqlite fails with "converting NULL to string is unsupported"

### ISSUE THREAD

**Issue by tcanabrava** [k1LoW/tbls#578]
```
➜  database-spec git:(master) ✗ tbls out -t svg -o output           
sql: Scan error on column index 2, name "name": converting NULL to string is unsupported

➜  database-spec git:(master) ✗ tbls version 
1.74.1

➜  database-spec git:(master) ✗ cat tbls.yml 
dsn: sq:///home/tcanabrava/cad_database.db
```
I tried to fix the error but my go-foo is really really bad, and I couldn't make the debugger work, sorry.

A zip file of the database to help.
[cad_database.db.zip](https://github.com/k1LoW/tbls/files/15176658/cad_database.db.zip)

**Comment by k1LoW** [comment]
@tcanabrava Thank you for your report. I could see the error too.
